### ISSUE TITLE
When es upgrade to 2.x, you need to install plug-ins can use this module ?

### ISSUE THREAD

**Issue by occultskyrong** [dermidgen/elasticsearch-deletebyquery#1]
### First of all thank you for this open source module

I use this plugin on es1.5.0, npm install this module can be used directly.

But after I upgrade to es2.3.4 , will perform the same js error, then google it, in stackoverflow someone says you need to install the plugin.

[/plugin install delete-by-query](http://stackoverflow.com/questions/37177359/how-to-delete-document-matching-a-query-using-official-elasticsearch-nodejs-clie)

Also in this module in the readme sentence:
`
This module provides the deleteByQuery method which was removed from the core API in ES 2.0.0. For those with the Delete-by-query installed, this will bring back that feature to your Elasticsearch-js client.
`

After 2.x, use this module you need to install es the plugin, it should be this way?

 I propose to add a hint to the readme~

**Comment by dermidgen** [comment]
Thank you,

deleteByQuery functionality was moved to a server-side plugin as of ES >=2.x. Yes, you must install the server-side plugin.

This package assumes you have installed the plugin and are trying to use the feature from the client; which does not offer deleteByQuery by default.

See [ES Delete By Query documentation](https://www.elastic.co/guide/en/elasticsearch/plugins/2.3/plugins-delete-by-query.html).

I will link this reference in the README.  Thank you.

**Comment by occultskyrong** [comment]
:smile:
